return {
    "nvim-lua/plenary.nvim",
    "nvim-lua/popup.nvim",
    "nvim-treesitter/playground",
    "romgrk/nvim-treesitter-context",
    "folke/tokyonight.nvim",
    "themercorp/themer.lua",
    'nvim-lualine/lualine.nvim',
    "sbdchd/neoformat",
    "TimUntersberger/neogit",
    "windwp/nvim-autopairs",
    "xiyaowong/nvim-transparent",
    'L3MON4D3/LuaSnip',
    'rafamadriz/friendly-snippets',
    'onsails/lspkind-nvim',
    'folke/neodev.nvim',
}
